name: roadproject
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy
  - pillow
  - pyproj
  - shapely
  - matplotlib
  - scikit-learn
  - opencv
  - osmnx
  - utm
  - pip
  - pip:
      - imutils
      - tensorflow
      - keras